#### Enviroment Value####
X_MIN = 110
X_MAX = 800
Y_MIN = 40
Y_MAX = 1250
Z_FLOOR = -843
Z_FLOOR_MOVING = Z_FLOOR+700
#### SIDE 
X_BENKI_RIGHT_SIDE=120
X_BENKI_LEFT_SIDE=750
Y_BENKI_SIDE=800


#### BENKI FRONT####
Y_BENKI_FRONT_EE_SIDE=920
Y_BANKI_FRONT_EE_KERCHER=840
X_BENKI_FRONT=int((X_MIN+X_MAX)/2)
X_FRONT_FLOOR_MIN=X_MIN
X_FRONT_FLOOR_MAX=X_MAX-30#ok

#### BENKI TOP####
Z_BENKI = -275#ok
Y_BENKI_TOP_MIN=480
Y_BENKI_TOP_MAX=950#ok
#### OTHER ####
Y_EVACUATION = 1000

#### Machine Value####
ANGLE_EE_RIGHT=2120
ANGLE_EE_CENTER=1575
ANGLE_EE_LEFT=1050
# KARCHER = 20


# need to check
#### field val ####
X_MIN = 100 # same val
X_MAX = 830 # same val
FIELD_X = X_MAX + X_MIN
Y_MIN = Y_MIN
Y_MAX = Y_MAX
Z_MIN = -840
Z_MAX = -10
Z_CUP = Z_MIN + 150
BENKI_X = 310
FRONT_PROHIBITION_X_MIN = 150 # FIELD_X/2 - BENKI_X/2
FRONT_PROHIBITION_X_MAX = 740 # FIELD_X/2 + BENKI_X/2
# RIGHT_SIDE_PROHIBITION_X_MIN = 450
# RIGHT_SIDE_PROHIBITION_X_MAX = FRONT_PROHIBITION_X_MIN
# LEFT_SIDE_PROHIBITION_X_MIN = FRONT_PROHIBITION_X_MAX
# LEFT_SIDE_PROHIBITION_X_MAX = FIELD_X - RIGHT_SIDE_PROHIBITION_X_MIN
FRONT_PROHIBITION_Y_MAX = 900